### Get all categories
GET http://localhost:3000/api/categories
Accept: application/json

### Create new category
POST http://localhost:3000/api/categories
Accept: application/json
Content-Type: application/json

{
    "name": "HP"
}

### Get category by id
GET http://localhost:3000/api/categories/19
Accept: application/json

### Update category by id
PUT http://localhost:3000/api/categories/6
Accept: application/json
Content-Type: application/json

{
    "name": "Smartphone"
}

### Delete category by id
DELETE http://localhost:3000/api/categories/4
Accept: application/json
